#!/usr/bin/env perl

use strict;
use warnings;

BEGIN {
    use File::Basename 'dirname';
    use File::Spec::Functions qw/catdir splitdir/;

    my @dir = splitdir( dirname( __FILE__ ) );
    push @dir, ".." while -e join '/', @dir and not -e join '/', @dir, 'lib';
    unshift @INC, join '/', @dir, $_ for '.inc', 'lib';

    $ENV{MOJO_MODE}  ||= $ARGV[ -1 ] && $ARGV[ -1 ] eq 'production' ? 'production' : 'development';
    $ENV{DBIC_TRACE} ||= "1=". join '/', @dir, qw/log database.log/ if $ENV{MOJO_MODE} eq 'development';
}

require Mojolicious::Commands;
Mojolicious::Commands->start_app( 'QuranAPI' );
